Repository Kernel360/KDEV5-MY-WORK-BE, pull requests merged in 2025-07, with the labels that each got.

#299 [feat] 안읽은 알림 개수 조회 API 추가 (#298)
  src/main/java/kr/mywork/domain/notification/repository/NotificationRepository.java
  src/main/java/kr/mywork/domain/notification/service/NotificationService.java
  src/main/java/kr/mywork/infrastructure/notification/rdb/QueryDslNotificationRepository.java
  src/main/java/kr/mywork/interfaces/notification/controller/NotificationController.java
Labels: feature, api

#306 [bug] 프로젝트 스탭 갯수 조회시 삭제된건은 제외
  src/main/java/kr/mywork/infrastructure/post/rdb/QueryDslPostRepository.java
Labels: project_step

#304 [fix] 리뷰에 작성자 이름과 회사 이름이 반대로 들어가는 이슈
  src/main/java/kr/mywork/domain/post/service/dto/request/ReviewCreateRequest.java
Labels: bug

#314 [build] main branch 푸시할 경우 CI/CD 자동화 설정
  .github/workflows/backend-cicd.yml
Labels: build

#352 [chore]: '.DS_Store' 파일을 git ignore에 추가
  .gitignore
Labels: chore
