Repository Kernel360/KDEV5-MY-WORK-BE, pull requests merged in 2025-06, with the labels that each got.

#71 [feat] 프로젝트 도메인 엔티티 및 디렉토리 구조 추가 #70
  src/main/java/kr/mywork/domain/project/errors/.gitkeep
  src/main/java/kr/mywork/domain/project/model/Project.java
  src/main/java/kr/mywork/domain/project/model/ProjectAssign.java
  src/main/java/kr/mywork/domain/project/model/ProjectMember.java
  src/main/java/kr/mywork/domain/project/repository/ProjectRepository.java
  src/main/java/kr/mywork/domain/project/service/ProjectService.java
  src/main/java/kr/mywork/domain/project/service/dto/request/.gitkeep
  src/main/java/kr/mywork/domain/project/service/dto/response/.gitkeep
  src/main/java/kr/mywork/infrastructure/projecet/rdb/.gitkeep
  src/main/java/kr/mywork/interfaces/project/controller/ProjectController.java
  src/main/java/kr/mywork/interfaces/project/dto/reponse/.gitkeep
  src/main/java/kr/mywork/interfaces/project/dto/request/.gitkeep
  src/test/java/kr/mywork/docs/ProjectDocumentationTest.java
Labels: project

#80 [feat] 로그인 성공 응답에 사용자 정보를 추가하고, 로컬 개발 환경에서의 CORS 설정을 개선(#73)
  src/main/java/kr/mywork/common/api/config/CorsConfig.java
  src/main/java/kr/mywork/common/api/config/WebConfig.java
  src/main/java/kr/mywork/common/auth/config/SecurityConfig.java
  src/main/java/kr/mywork/domain/auth/dto/MemberDetails.java
  src/main/java/kr/mywork/domain/auth/dto/response/TokenResponse.java
  src/main/java/kr/mywork/domain/auth/service/JwtTokenProvider.java
  src/main/java/kr/mywork/domain/auth/service/MemberDetailService.java
  src/main/java/kr/mywork/domain/auth/service/TokenAuthenticationService.java
  src/main/java/kr/mywork/domain/auth/service/TokenService.java
  src/main/java/kr/mywork/interfaces/auth/dto/response/TokenWebResponse.java
  src/main/java/kr/mywork/interfaces/auth/filter/JwtAuthenticationFilter.java
  src/main/java/kr/mywork/interfaces/auth/handler/success/LoginSuccessHandler.java
  src/test/java/kr/mywork/docs/AuthDocumentationTest.java
  src/test/java/kr/mywork/docs/CompanyDocumentationTest.java
  src/test/java/kr/mywork/docs/MemberDocumentationTest.java
  src/test/java/kr/mywork/docs/PostDocumentationTest.java
  src/test/java/kr/mywork/docs/ProjectStepDocumentationTest.java
  src/test/java/kr/mywork/docs/ReviewDocumentationTest.java
  src/test/java/kr/mywork/infrastructure/company/rdb/QueryDslCompanyRepositoryTest.java
  src/test/java/kr/mywork/interfaces/post/controller/ReviewControllerTest.java
  src/test/java/kr/mywork/interfaces/project_step/controller/ProjectStepControllerTest.java
Labels: auth

#77 [feat] 프로젝트 멤버 조회 API
  src/main/java/kr/mywork/domain/member/repository/MemberRepository.java
  src/main/java/kr/mywork/domain/project/service/ProjectService.java
  src/main/java/kr/mywork/domain/project/service/dto/response/ProjectMemberResponse.java
  src/main/java/kr/mywork/infrastructure/member/rdb/QueryDslMemberRepository.java
  src/main/java/kr/mywork/infrastructure/project/rdb/.gitkeep
  src/main/java/kr/mywork/interfaces/project/controller/ProjectController.java
  src/main/java/kr/mywork/interfaces/project/dto/reponse/.gitkeep
  src/main/java/kr/mywork/interfaces/project/dto/response/ProjectMemberListWebResponse.java
  src/main/java/kr/mywork/interfaces/project/dto/response/ProjectMemberWebResponse.java
  src/test/java/kr/mywork/docs/ProjectDocumentationTest.java
  src/test/resources/sql/project-for-member-list.sql
Labels: api, project

#99 [refactor] 회사 URL root path 변경 (#98)
  src/main/java/kr/mywork/interfaces/company/controller/CompanyController.java
  src/test/java/kr/mywork/docs/CompanyDocumentationTest.java
Labels: api

#95 체크리스트 상세조회 API
  src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListErrorCode.java
  src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListErrorType.java
  src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListException.java
  src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListNotFoundException.java
  src/main/java/kr/mywork/domain/project_checklist/model/ProjectCheckList.java
  src/main/java/kr/mywork/domain/project_checklist/repository/ProjectCheckListRepository.java
  src/main/java/kr/mywork/domain/project_checklist/service/ProjectCheckListService.java
  src/main/java/kr/mywork/domain/project_checklist/service/dto/request/ProjectCheckListCreateRequest.java
  src/main/java/kr/mywork/domain/project_checklist/service/dto/response/ProjectCheckListCreateResponse.java
  src/main/java/kr/mywork/domain/project_checklist/service/dto/response/ProjectCheckListDetailResponse.java
  src/main/java/kr/mywork/infrastructure/project_checklist/rdb/QueryDslProjectCheckListRepository.java
  src/main/java/kr/mywork/interfaces/project_checklist/controller/ProjectCheckListController.java
  src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/request/ProjectCheckListCreateWebRequest.java
  src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/response/ProjectCheckListCreateWebResponse.java
  src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/response/ProjectCheckListDetailWebResponse.java
  src/test/java/kr/mywork/docs/ProjectCheckListDocumentationTest.java
  src/test/resources/sql/project-check-list-for-get.sql
Labels: api, project_check_list

#123 fix: 프로젝트 스탭 생성시 projectId 추가
  src/main/java/kr/mywork/domain/project_step/model/ProjectStep.java
  src/main/java/kr/mywork/domain/project_step/serivce/ProjectStepService.java
  src/main/java/kr/mywork/domain/project_step/serivce/dto/request/ProjectStepCreateRequest.java
Labels: bug, api, project

#128 [fix] 프로젝트 스탭 엔티티 수정
  src/main/java/kr/mywork/domain/project_step/model/ProjectStep.java
Labels: bug, api, project

#131 [chore] 시스템 어드민 샘플 데이터 추가
  src/main/resources/data.sql
Labels: chore

#142 [feat] 회사 목록 조회 응답 필드로 회사 아이디 추가
  src/main/java/kr/mywork/domain/company/service/dto/response/CompanySelectResponse.java
  src/main/java/kr/mywork/infrastructure/company/rdb/QueryDslCompanyRepository.java
  src/main/java/kr/mywork/interfaces/company/controller/dto/response/CompanySelectWebResponse.java
  src/test/java/kr/mywork/docs/CompanyDocumentationTest.java
Labels: company, api

#144 [feat] 회사 사원 목록 조회 URL 변경
  src/main/java/kr/mywork/interfaces/company/controller/CompanyController.java
  src/main/java/kr/mywork/interfaces/member/controller/MemberController.java
  src/test/java/kr/mywork/docs/CompanyDocumentationTest.java
  src/test/java/kr/mywork/docs/MemberDocumentationTest.java
Labels: company, api

#141 chore : 프로젝트 초기 세팅을 위한 샘플 데이터 쿼리문 추가
  src/main/resources/data.sql
Labels: chore

#167 [feat] 임시 CORS 허용 URL 추가
  src/main/java/kr/mywork/common/auth/config/SecurityConfig.java
Labels: feature

#191 [fix] 게시글이 삭제되지 않는 이슈 해결 (#190)
  src/main/java/kr/mywork/domain/post/model/Post.java
  src/main/java/kr/mywork/domain/post/service/PostService.java
Labels: bug

#195 [fix] 샘플데이터 누락데이터 추가
  src/main/resources/data.sql
Labels: bug

#203 [refactor] 날짜 관련 필드 suffix 공통화
  src/main/java/kr/mywork/domain/member/model/Member.java
  src/main/java/kr/mywork/domain/member/service/MemberService.java
  src/main/java/kr/mywork/domain/member/service/dto/request/MemberUpdateRequest.java
  src/main/java/kr/mywork/interfaces/member/controller/dto/request/MemberUpdateWebRequest.java
  src/main/java/kr/mywork/interfaces/member/controller/dto/response/MemberDetailsWebResponse.java
  src/test/java/kr/mywork/docs/MemberDocumentationTest.java
Labels: refactor

#209 feat: kbe-mywork.com CORS 추가 (#208)
  src/main/java/kr/mywork/common/auth/config/SecurityConfig.java
Labels: feature

#219 [feat]대시보드 마감 임박 프로젝트 조회 API 구현 (#214)
  src/main/java/kr/mywork/domain/project/repository/ProjectAssignRepository.java
  src/main/java/kr/mywork/domain/project/repository/ProjectRepository.java
  src/main/java/kr/mywork/domain/project/service/ProjectService.java
  src/main/java/kr/mywork/domain/project/service/dto/request/NearDeadlineProjectRequest.java
  src/main/java/kr/mywork/domain/project/service/dto/response/NearDeadlineProjectResponse.java
  src/main/java/kr/mywork/domain/project_member/repository/ProjectMemberRepository.java
  src/main/java/kr/mywork/infrastructure/project/rdb/QueryDslProjectAssignRepository.java
  src/main/java/kr/mywork/infrastructure/project/rdb/QueryDslProjectRepository.java
  src/main/java/kr/mywork/infrastructure/project_member/rdb/QueryDslProjectMemberRepository.java
  src/main/java/kr/mywork/interfaces/dashboard/controller/DashboardController.java
  src/main/java/kr/mywork/interfaces/dashboard/controller/dto/response/NearDeadlineProjectListWebResponse.java
  src/main/java/kr/mywork/interfaces/dashboard/controller/dto/response/NearDeadlineProjectWebResponse.java
  src/main/resources/application.yml
  src/test/java/kr/mywork/docs/DashboardDocumentationTest.java
  src/test/resources/application.yml
  src/test/resources/sql/project-near-deadline.sql
Labels: feature, api, dashboard

#228 [build] spring.config.location 으로 실행 방식 변경
  scripts/start.sh
Labels: build

#238 [fix] 이미지 업로드 및 로그 관리 병합 충돌 이슈 해결 (#237)
  src/main/java/kr/mywork/domain/company/model/Company.java
Labels: bug, build

#282 localstack container CORS 환경변수 추가
  docker/docker-compose.yml
Labels: bug

#284 [chore] 프로젝트 업데이트시 필드추가 (amount)
  src/main/java/kr/mywork/domain/project/model/Project.java
Labels: project, chore
